// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	chat "sciedu-backend/internal/chat"

	mock "github.com/stretchr/testify/mock"
)

// LLMProvider is an autogenerated mock type for the LLMProvider type
type LLMProvider struct {
	mock.Mock
}

// StreamChat provides a mock function with given fields: ctx, req
func (_m *LLMProvider) StreamChat(ctx context.Context, req chat.CreateChatCompletionRequest) (<-chan chat.ChatCompletionChunk, <-chan error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StreamChat")
	}

	var r0 <-chan chat.ChatCompletionChunk
	var r1 <-chan error
	if rf, ok := ret.Get(0).(func(context.Context, chat.CreateChatCompletionRequest) (<-chan chat.ChatCompletionChunk, <-chan error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.CreateChatCompletionRequest) <-chan chat.ChatCompletionChunk); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan chat.ChatCompletionChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.CreateChatCompletionRequest) <-chan error); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}

// NewLLMProvider creates a new instance of LLMProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLLMProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *LLMProvider {
	mock := &LLMProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
