// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answer_queries.sql

package question

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (question_id, user_id, selected_option_id, text_answer)
VALUES ($1, $2, $3, $4)
RETURNING id, question_id, user_id, selected_option_id, text_answer, created_at, updated_at
`

type CreateAnswerParams struct {
	QuestionID       uuid.UUID
	UserID           uuid.UUID
	SelectedOptionID pgtype.UUID
	TextAnswer       pgtype.Text
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.QuestionID,
		arg.UserID,
		arg.SelectedOptionID,
		arg.TextAnswer,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.UserID,
		&i.SelectedOptionID,
		&i.TextAnswer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnswersByQuestion = `-- name: ListAnswersByQuestion :many
SELECT id, question_id, user_id, selected_option_id, text_answer, created_at, updated_at
FROM answers
WHERE question_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAnswersByQuestion(ctx context.Context, questionID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.UserID,
			&i.SelectedOptionID,
			&i.TextAnswer,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
