// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: correct_answer_queries.sql

package question

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCorrectAnswer = `-- name: GetCorrectAnswer :one
SELECT question_id, type, selected_option_id, reference_answer, version,
       answer_result_sync_status, updated_at
FROM correct_answers WHERE question_id = $1
`

func (q *Queries) GetCorrectAnswer(ctx context.Context, questionID uuid.UUID) (CorrectAnswer, error) {
	row := q.db.QueryRow(ctx, getCorrectAnswer, questionID)
	var i CorrectAnswer
	err := row.Scan(
		&i.QuestionID,
		&i.Type,
		&i.SelectedOptionID,
		&i.ReferenceAnswer,
		&i.Version,
		&i.AnswerResultSyncStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const pendingAnswerSynchronizations = `-- name: PendingAnswerSynchronizations :many
SELECT question_id, version FROM correct_answers
WHERE answer_result_sync_status = 'PENDING'
ORDER BY updated_at, question_id
LIMIT 100
`

type PendingAnswerSynchronizationsRow struct {
	QuestionID uuid.UUID
	Version    int64
}

func (q *Queries) PendingAnswerSynchronizations(ctx context.Context) ([]PendingAnswerSynchronizationsRow, error) {
	rows, err := q.db.Query(ctx, pendingAnswerSynchronizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAnswerSynchronizationsRow
	for rows.Next() {
		var i PendingAnswerSynchronizationsRow
		if err := rows.Scan(&i.QuestionID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnswerResultSyncStatusForVersion = `-- name: UpdateAnswerResultSyncStatusForVersion :one
UPDATE correct_answers
SET answer_result_sync_status = $1, updated_at = NOW()
WHERE question_id = $2 AND version = $3
  AND ($1 <> 'FAILED' OR answer_result_sync_status = 'PENDING')
RETURNING question_id, type, selected_option_id, reference_answer, version,
          answer_result_sync_status, updated_at
`

type UpdateAnswerResultSyncStatusForVersionParams struct {
	Status        string
	QuestionID    uuid.UUID
	TargetVersion int64
}

func (q *Queries) UpdateAnswerResultSyncStatusForVersion(ctx context.Context, arg UpdateAnswerResultSyncStatusForVersionParams) (CorrectAnswer, error) {
	row := q.db.QueryRow(ctx, updateAnswerResultSyncStatusForVersion, arg.Status, arg.QuestionID, arg.TargetVersion)
	var i CorrectAnswer
	err := row.Scan(
		&i.QuestionID,
		&i.Type,
		&i.SelectedOptionID,
		&i.ReferenceAnswer,
		&i.Version,
		&i.AnswerResultSyncStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCorrectAnswer = `-- name: UpsertCorrectAnswer :one
WITH eligible AS (
    SELECT EXISTS (
        SELECT 1 FROM answers AS a
         JOIN experiments AS e ON e.id = a.experiment_id
         LEFT JOIN answer_results AS ar ON ar.answer_id = a.id
        WHERE a.question_id = $1
          AND $2 = 'CHOICE'
           AND e.configuration->>'gradingMode' = 'AUTOMATIC'
           AND a.selected_option_id IS NOT NULL
           AND ar.method IS DISTINCT FROM 'MANUAL'
    ) AS present
)
INSERT INTO correct_answers (question_id, type, selected_option_id, reference_answer, answer_result_sync_status)
SELECT $1, $2, $3,
       $4, CASE WHEN eligible.present THEN 'PENDING' ELSE 'SYNCED' END
FROM eligible
ON CONFLICT (question_id) DO UPDATE
SET type = EXCLUDED.type,
    selected_option_id = EXCLUDED.selected_option_id,
    reference_answer = EXCLUDED.reference_answer,
    version = CASE WHEN correct_answers.type = EXCLUDED.type
      AND correct_answers.selected_option_id IS NOT DISTINCT FROM EXCLUDED.selected_option_id
      AND correct_answers.reference_answer IS NOT DISTINCT FROM EXCLUDED.reference_answer
      THEN correct_answers.version ELSE correct_answers.version + 1 END,
    answer_result_sync_status = CASE WHEN correct_answers.type = EXCLUDED.type
      AND correct_answers.selected_option_id IS NOT DISTINCT FROM EXCLUDED.selected_option_id
      AND correct_answers.reference_answer IS NOT DISTINCT FROM EXCLUDED.reference_answer
      AND correct_answers.answer_result_sync_status <> 'FAILED'
      THEN correct_answers.answer_result_sync_status ELSE EXCLUDED.answer_result_sync_status END,
    updated_at = CASE WHEN correct_answers.type = EXCLUDED.type
      AND correct_answers.selected_option_id IS NOT DISTINCT FROM EXCLUDED.selected_option_id
      AND correct_answers.reference_answer IS NOT DISTINCT FROM EXCLUDED.reference_answer
      AND correct_answers.answer_result_sync_status <> 'FAILED'
      THEN correct_answers.updated_at ELSE NOW() END
RETURNING question_id, type, selected_option_id, reference_answer, version,
          answer_result_sync_status, updated_at
`

type UpsertCorrectAnswerParams struct {
	QuestionID       uuid.UUID
	Type             string
	SelectedOptionID pgtype.UUID
	ReferenceAnswer  pgtype.Text
}

func (q *Queries) UpsertCorrectAnswer(ctx context.Context, arg UpsertCorrectAnswerParams) (CorrectAnswer, error) {
	row := q.db.QueryRow(ctx, upsertCorrectAnswer,
		arg.QuestionID,
		arg.Type,
		arg.SelectedOptionID,
		arg.ReferenceAnswer,
	)
	var i CorrectAnswer
	err := row.Scan(
		&i.QuestionID,
		&i.Type,
		&i.SelectedOptionID,
		&i.ReferenceAnswer,
		&i.Version,
		&i.AnswerResultSyncStatus,
		&i.UpdatedAt,
	)
	return i, err
}
