// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package question

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Content struct {
	ID      uuid.UUID
	Type    interface{}
	Content pgtype.Text
}

type Message struct {
	ID         uuid.UUID
	ChatID     uuid.UUID
	PreviousID pgtype.UUID
	Content    pgtype.Text
	Role       string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type Option struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Content    string
	Label      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Question struct {
	ID        uuid.UUID
	Content   string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
