// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question_queries.sql

package question

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (type, content)
VALUES ($1, $2)
RETURNING id, content, type, created_at, updated_at
`

type CreateQuestionParams struct {
	Type    string
	Content string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, arg.Type, arg.Content)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, content, type, created_at, updated_at
FROM questions
WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestion = `-- name: ListQuestion :many
SELECT id, content, type, created_at, updated_at
FROM questions
ORDER BY id
`

func (q *Queries) ListQuestion(ctx context.Context) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET type = $2,
    content = $3
WHERE id = $1
RETURNING id, content, type, created_at, updated_at
`

type UpdateQuestionParams struct {
	ID      uuid.UUID
	Type    string
	Content string
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion, arg.ID, arg.Type, arg.Content)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
