// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: block_queries.sql

package page

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContentBlock = `-- name: CreateContentBlock :one
INSERT INTO page_blocks (page_id, content_id, display_order, required)
VALUES ($1, $2, $3, $4)
RETURNING id, page_id, content_id, question_id, display_order, required, created_at, updated_at
`

type CreateContentBlockParams struct {
	PageID       uuid.UUID
	ContentID    pgtype.UUID
	DisplayOrder int32
	Required     bool
}

func (q *Queries) CreateContentBlock(ctx context.Context, arg CreateContentBlockParams) (PageBlock, error) {
	row := q.db.QueryRow(ctx, createContentBlock,
		arg.PageID,
		arg.ContentID,
		arg.DisplayOrder,
		arg.Required,
	)
	var i PageBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ContentID,
		&i.QuestionID,
		&i.DisplayOrder,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestionBlock = `-- name: CreateQuestionBlock :one
INSERT INTO page_blocks (page_id, question_id, display_order, required)
VALUES ($1, $2, $3, $4)
RETURNING id, page_id, content_id, question_id, display_order, required, created_at, updated_at
`

type CreateQuestionBlockParams struct {
	PageID       uuid.UUID
	QuestionID   pgtype.UUID
	DisplayOrder int32
	Required     bool
}

func (q *Queries) CreateQuestionBlock(ctx context.Context, arg CreateQuestionBlockParams) (PageBlock, error) {
	row := q.db.QueryRow(ctx, createQuestionBlock,
		arg.PageID,
		arg.QuestionID,
		arg.DisplayOrder,
		arg.Required,
	)
	var i PageBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ContentID,
		&i.QuestionID,
		&i.DisplayOrder,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :execrows
DELETE FROM page_blocks
WHERE id = $1
  AND page_id = $2
`

type DeleteBlockParams struct {
	ID     uuid.UUID
	PageID uuid.UUID
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlock, arg.ID, arg.PageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlockByID = `-- name: GetBlockByID :one
SELECT id, page_id, content_id, question_id, display_order, required, created_at, updated_at
FROM page_blocks
WHERE id = $1
`

func (q *Queries) GetBlockByID(ctx context.Context, id uuid.UUID) (PageBlock, error) {
	row := q.db.QueryRow(ctx, getBlockByID, id)
	var i PageBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ContentID,
		&i.QuestionID,
		&i.DisplayOrder,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlocksByPage = `-- name: ListBlocksByPage :many
SELECT id, page_id, content_id, question_id, display_order, required, created_at, updated_at
FROM page_blocks
WHERE page_id = $1
ORDER BY display_order
`

func (q *Queries) ListBlocksByPage(ctx context.Context, pageID uuid.UUID) ([]PageBlock, error) {
	rows, err := q.db.Query(ctx, listBlocksByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageBlock
	for rows.Next() {
		var i PageBlock
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ContentID,
			&i.QuestionID,
			&i.DisplayOrder,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBlockOrders = `-- name: SetBlockOrders :many
UPDATE page_blocks
SET display_order = data.ord - 1,
    updated_at = NOW()
FROM unnest($2::uuid[]) WITH ORDINALITY AS data(id, ord)
WHERE page_blocks.id = data.id
  AND page_blocks.page_id = $1
RETURNING page_blocks.id, page_blocks.page_id, page_blocks.content_id, page_blocks.question_id,
          page_blocks.display_order, page_blocks.required, page_blocks.created_at, page_blocks.updated_at
`

type SetBlockOrdersParams struct {
	PageID   uuid.UUID
	BlockIds []uuid.UUID
}

// Array position becomes the new display_order. The unique constraint is
// deferred by the caller and rechecked when the transaction commits.
func (q *Queries) SetBlockOrders(ctx context.Context, arg SetBlockOrdersParams) ([]PageBlock, error) {
	rows, err := q.db.Query(ctx, setBlockOrders, arg.PageID, arg.BlockIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageBlock
	for rows.Next() {
		var i PageBlock
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ContentID,
			&i.QuestionID,
			&i.DisplayOrder,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentBlock = `-- name: UpdateContentBlock :one
UPDATE page_blocks
SET content_id = $2,
    question_id = NULL,
    display_order = $3,
    required = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, page_id, content_id, question_id, display_order, required, created_at, updated_at
`

type UpdateContentBlockParams struct {
	ID           uuid.UUID
	ContentID    pgtype.UUID
	DisplayOrder int32
	Required     bool
}

func (q *Queries) UpdateContentBlock(ctx context.Context, arg UpdateContentBlockParams) (PageBlock, error) {
	row := q.db.QueryRow(ctx, updateContentBlock,
		arg.ID,
		arg.ContentID,
		arg.DisplayOrder,
		arg.Required,
	)
	var i PageBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ContentID,
		&i.QuestionID,
		&i.DisplayOrder,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestionBlock = `-- name: UpdateQuestionBlock :one
UPDATE page_blocks
SET question_id = $2,
    content_id = NULL,
    display_order = $3,
    required = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, page_id, content_id, question_id, display_order, required, created_at, updated_at
`

type UpdateQuestionBlockParams struct {
	ID           uuid.UUID
	QuestionID   pgtype.UUID
	DisplayOrder int32
	Required     bool
}

func (q *Queries) UpdateQuestionBlock(ctx context.Context, arg UpdateQuestionBlockParams) (PageBlock, error) {
	row := q.db.QueryRow(ctx, updateQuestionBlock,
		arg.ID,
		arg.QuestionID,
		arg.DisplayOrder,
		arg.Required,
	)
	var i PageBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ContentID,
		&i.QuestionID,
		&i.DisplayOrder,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
