// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_queries.sql

package page

import (
	"context"

	"github.com/google/uuid"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (course_id, title, display_order)
VALUES ($1, $2, $3)
RETURNING id, course_id, title, display_order, created_at, updated_at
`

type CreatePageParams struct {
	CourseID     uuid.UUID
	Title        string
	DisplayOrder int32
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage, arg.CourseID, arg.Title, arg.DisplayOrder)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deferOrderConstraints = `-- name: DeferOrderConstraints :exec
SET CONSTRAINTS ALL DEFERRED
`

// Both deferrable constraints in this schema are display-order uniqueness
// constraints. Defer them until commit so reorder cycles can move directly to
// their final positions.
func (q *Queries) DeferOrderConstraints(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deferOrderConstraints)
	return err
}

const deletePage = `-- name: DeletePage :execrows
DELETE FROM pages
WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, course_id, title, display_order, created_at, updated_at
FROM pages
WHERE id = $1
`

func (q *Queries) GetPageByID(ctx context.Context, id uuid.UUID) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPagesByCourse = `-- name: ListPagesByCourse :many
SELECT id, course_id, title, display_order, created_at, updated_at
FROM pages
WHERE course_id = $1
ORDER BY display_order
`

func (q *Queries) ListPagesByCourse(ctx context.Context, courseID uuid.UUID) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPagesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPageOrders = `-- name: SetPageOrders :many
UPDATE pages
SET display_order = data.ord - 1,
    updated_at = NOW()
FROM unnest($2::uuid[]) WITH ORDINALITY AS data(id, ord)
WHERE pages.id = data.id
  AND pages.course_id = $1
RETURNING pages.id, pages.course_id, pages.title, pages.display_order, pages.created_at, pages.updated_at
`

type SetPageOrdersParams struct {
	CourseID uuid.UUID
	PageIds  []uuid.UUID
}

// Array position becomes the new display_order. The unique constraint is
// deferred by the caller and rechecked when the transaction commits.
func (q *Queries) SetPageOrders(ctx context.Context, arg SetPageOrdersParams) ([]Page, error) {
	rows, err := q.db.Query(ctx, setPageOrders, arg.CourseID, arg.PageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = $2,
    display_order = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, course_id, title, display_order, created_at, updated_at
`

type UpdatePageParams struct {
	ID           uuid.UUID
	Title        string
	DisplayOrder int32
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage, arg.ID, arg.Title, arg.DisplayOrder)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
