// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package questions

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID               uuid.UUID
	QuestionID       uuid.UUID
	SelectedOptionID *uuid.UUID
	TextAnswer       string
	CreatedAt        pgtype.Timestamptz
}

type Option struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Label      string
	Content    string
}

type Question struct {
	ID      uuid.UUID
	Type    string
	Content string
}
