// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package questions

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Option struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Content    string
	Label      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Question struct {
	ID        uuid.UUID
	Content   string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
