// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: option_queries.sql

package questions

import (
	"context"

	"github.com/google/uuid"
)

const createOption = `-- name: CreateOption :one
INSERT INTO options (question_id, label, content)
VALUES ($1, $2, $3)
RETURNING id, question_id, label, content
`

type CreateOptionParams struct {
	QuestionID uuid.UUID
	Label      string
	Content    string
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, createOption, arg.QuestionID, arg.Label, arg.Content)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Label,
		&i.Content,
	)
	return i, err
}

const deleteOption = `-- name: DeleteOption :exec
DELETE FROM options
WHERE id = $1
`

func (q *Queries) DeleteOption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOption, id)
	return err
}

const getOption = `-- name: GetOption :one
SELECT id, question_id, label, content
FROM options
WHERE id = $1
`

func (q *Queries) GetOption(ctx context.Context, id uuid.UUID) (Option, error) {
	row := q.db.QueryRow(ctx, getOption, id)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Label,
		&i.Content,
	)
	return i, err
}

const listOptionsByQuestion = `-- name: ListOptionsByQuestion :many
SELECT id, question_id, label, content
FROM options
WHERE question_id = $1
ORDER BY label
`

func (q *Queries) ListOptionsByQuestion(ctx context.Context, questionID uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Label,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOption = `-- name: UpdateOption :one
UPDATE options
SET label = $2,
    content = $3
WHERE id = $1
RETURNING id, question_id, label, content
`

type UpdateOptionParams struct {
	ID      uuid.UUID
	Label   string
	Content string
}

func (q *Queries) UpdateOption(ctx context.Context, arg UpdateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, updateOption, arg.ID, arg.Label, arg.Content)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Label,
		&i.Content,
	)
	return i, err
}
