#!/usr/bin/env bash

# This script merges all schema.sql files found in the internal directory and subdirectories into a single SQL file.
# It is used to create a full schema file for sqlc.

set -euo pipefail

# Default values
OUTPUT_FILE="./internal/database/full_schema.sql"
SQLC_YAML="./sqlc.yaml"

# Print help message
print_help() {
    echo "Usage: $0 [options]"
    echo
    echo "Options:"
    echo "  --output-file PATH     Path to the merged schema output file (default: ./internal/database/full_schema.sql)"
    echo "  --sqlc-yaml PATH       Path to the generated sqlc.yaml file (default: ./sqlc.yaml)"
    echo "  --help                 Show this help message and exit"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-file)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --sqlc-yaml)
            SQLC_YAML="$2"
            shift 2
            ;;
        --help)
            print_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            print_help
            exit 1
            ;;
    esac
done

SCHEMA_FILES=()
QUERY_FILES=()

# Automatically find all schema.sql files under internal directory (stable order)
mapfile -t SCHEMA_FILES < <(find ./internal -type f -name "schema.sql" | sort)

if [[ ${#SCHEMA_FILES[@]} -eq 0 ]]; then
    echo "No schema.sql files found under ./internal"
    exit 1
fi

# Clear and initialize the schema file
mkdir -p "$(dirname "$OUTPUT_FILE")"
echo -e "-- Code generated by schema merge script. DO NOT EDIT.\n" > "$OUTPUT_FILE"

# Merge schema files
for SCHEMA in "${SCHEMA_FILES[@]}"; do
    echo -e "\n-- Source: $SCHEMA" >> "$OUTPUT_FILE"
    cat "$SCHEMA" >> "$OUTPUT_FILE"
    echo >> "$OUTPUT_FILE"
done

# Start generating sqlc.yaml
mkdir -p "$(dirname "$SQLC_YAML")"
cat > "$SQLC_YAML" << 'EOF'
# Code generated by schema merge script. DO NOT EDIT.
version: "2"
sql:
EOF

# Find all sqlc query files (queries.sql and *_queries.sql) under internal directory.
# Excludes generated .go files by matching only *.sql.
mapfile -t QUERY_FILES < <(find ./internal -type f \( -name "queries.sql" -o -name "*_queries.sql" \) | sort)

if [[ ${#QUERY_FILES[@]} -eq 0 ]]; then
    echo "No query SQL files found (expected queries.sql or *_queries.sql under ./internal)"
    exit 1
fi

declare -A PACKAGE_QUERIES
declare -a PACKAGE_ORDER

for QUERY_FILE in "${QUERY_FILES[@]}"; do
    PACKAGE_DIR="$(dirname "$QUERY_FILE")"
    if [[ -z "${PACKAGE_QUERIES[$PACKAGE_DIR]+x}" ]]; then
        PACKAGE_QUERIES["$PACKAGE_DIR"]="$QUERY_FILE"
        PACKAGE_ORDER+=("$PACKAGE_DIR")
    else
        PACKAGE_QUERIES["$PACKAGE_DIR"]+=$'\n'"$QUERY_FILE"
    fi
done

for PACKAGE_DIR in "${PACKAGE_ORDER[@]}"; do
    PACKAGE_NAME="$(basename "$PACKAGE_DIR")"

    cat >> "$SQLC_YAML" << EOF
  - engine: "postgresql"
    queries:
EOF

    while IFS= read -r QUERY_FILE; do
        [[ -z "$QUERY_FILE" ]] && continue
        cat >> "$SQLC_YAML" << EOF
      - "$QUERY_FILE"
EOF
    done <<< "${PACKAGE_QUERIES[$PACKAGE_DIR]}"

    cat >> "$SQLC_YAML" << EOF
    schema: "$OUTPUT_FILE"
    gen:
      go:
        package: "$PACKAGE_NAME"
        out: "$PACKAGE_DIR"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
          - db_type: "content_type"
            go_type: "string"
EOF
done

echo "Generated merged schema at $OUTPUT_FILE"
echo "Generated sqlc config at $SQLC_YAML"
