// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentType string

const (
	ContentTypeTEXT  ContentType = "TEXT"
	ContentTypeMEDIA ContentType = "MEDIA"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType
	Valid       bool // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type Chat struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Content struct {
	ID      uuid.UUID
	Type    string
	Content string
}

type Message struct {
	ID         uuid.UUID
	ChatID     uuid.UUID
	PreviousID pgtype.UUID
	Content    pgtype.Text
	Role       string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	ProviderEmail  string
	EmailVerified  bool
	LastLoginAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OauthLoginState struct {
	StateHash    []byte
	Provider     string
	CodeVerifier string
	RedirectUrl  string
	ExpiresAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type Option struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Content    string
	Label      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Question struct {
	ID        uuid.UUID
	Content   string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID                 uuid.UUID
	FamilyID           uuid.UUID
	UserID             uuid.UUID
	TokenHash          []byte
	RotatedFromTokenID pgtype.UUID
	IsCurrent          bool
	IssuedAt           pgtype.Timestamptz
	UsedAt             pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type RefreshTokenFamily struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	OauthAccountID  pgtype.UUID
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	RevokedReason   pgtype.Text
	ReuseDetectedAt pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	IpAddress       *netip.Addr
	UserAgent       pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Email       string
	Name        string
	AvatarUrl   pgtype.Text
	Roles       []interface{}
	LastLoginAt pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
