// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Content struct {
	ID      uuid.UUID
	Type    interface{}
	Content pgtype.Text
}

type Message struct {
	ID         uuid.UUID
	ChatID     uuid.UUID
	PreviousID pgtype.UUID
	Content    pgtype.Text
	Role       string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	ProviderEmail  string
	EmailVerified  bool
	LastLoginAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OauthLoginState struct {
	StateHash    []byte
	Provider     string
	CodeVerifier string
	RedirectUrl  string
	ExpiresAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type Option struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Content    string
	Label      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Question struct {
	ID        uuid.UUID
	Content   string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID                 uuid.UUID
	FamilyID           uuid.UUID
	UserID             uuid.UUID
	TokenHash          []byte
	RotatedFromTokenID pgtype.UUID
	IsCurrent          bool
	IssuedAt           pgtype.Timestamptz
	UsedAt             pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type RefreshTokenFamily struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	OauthAccountID  pgtype.UUID
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	RevokedReason   pgtype.Text
	ReuseDetectedAt pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	IpAddress       *netip.Addr
	UserAgent       pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Email       string
	Name        string
	AvatarUrl   pgtype.Text
	Roles       []interface{}
	LastLoginAt pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
