// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pagevisit

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeOpenPageVisit = `-- name: CloseOpenPageVisit :one
UPDATE page_visits
SET left_at = $1
WHERE id = $2
  AND student_id = $3
  AND left_at IS NULL
RETURNING id, student_id, course_id, page_id, client_session_id, idempotency_key, entered_at, left_at
`

type CloseOpenPageVisitParams struct {
	LeftAt    pgtype.Timestamptz
	ID        uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) CloseOpenPageVisit(ctx context.Context, arg CloseOpenPageVisitParams) (PageVisit, error) {
	row := q.db.QueryRow(ctx, closeOpenPageVisit, arg.LeftAt, arg.ID, arg.StudentID)
	var i PageVisit
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.PageID,
		&i.ClientSessionID,
		&i.IdempotencyKey,
		&i.EnteredAt,
		&i.LeftAt,
	)
	return i, err
}

const countPageVisits = `-- name: CountPageVisits :one
SELECT count(*)
FROM page_visits
WHERE ($1::uuid IS NULL OR student_id = $1::uuid)
  AND ($2::uuid IS NULL OR course_id = $2::uuid)
  AND ($3::uuid IS NULL OR page_id = $3::uuid)
  AND ($4::uuid IS NULL OR client_session_id = $4::uuid)
  AND (
      $5::text IS NULL
      OR ($5::text = 'OPEN' AND left_at IS NULL)
      OR ($5::text = 'CLOSED' AND left_at IS NOT NULL)
  )
  AND ($6::timestamptz IS NULL OR entered_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR entered_at < $7::timestamptz)
`

type CountPageVisitsParams struct {
	StudentID       pgtype.UUID
	CourseID        pgtype.UUID
	PageID          pgtype.UUID
	ClientSessionID pgtype.UUID
	Status          pgtype.Text
	EnteredFrom     pgtype.Timestamptz
	EnteredBefore   pgtype.Timestamptz
}

func (q *Queries) CountPageVisits(ctx context.Context, arg CountPageVisitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPageVisits,
		arg.StudentID,
		arg.CourseID,
		arg.PageID,
		arg.ClientSessionID,
		arg.Status,
		arg.EnteredFrom,
		arg.EnteredBefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPageVisit = `-- name: CreatePageVisit :one
INSERT INTO page_visits (
    student_id,
    course_id,
    page_id,
    client_session_id,
    idempotency_key,
    entered_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, student_id, course_id, page_id, client_session_id, idempotency_key, entered_at, left_at
`

type CreatePageVisitParams struct {
	StudentID       uuid.UUID
	CourseID        uuid.UUID
	PageID          uuid.UUID
	ClientSessionID uuid.UUID
	IdempotencyKey  uuid.UUID
	EnteredAt       pgtype.Timestamptz
}

func (q *Queries) CreatePageVisit(ctx context.Context, arg CreatePageVisitParams) (PageVisit, error) {
	row := q.db.QueryRow(ctx, createPageVisit,
		arg.StudentID,
		arg.CourseID,
		arg.PageID,
		arg.ClientSessionID,
		arg.IdempotencyKey,
		arg.EnteredAt,
	)
	var i PageVisit
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.PageID,
		&i.ClientSessionID,
		&i.IdempotencyKey,
		&i.EnteredAt,
		&i.LeftAt,
	)
	return i, err
}

const leavePageVisitIfOpen = `-- name: LeavePageVisitIfOpen :one
UPDATE page_visits
SET left_at = $1
WHERE id = $2
  AND student_id = $3
  AND left_at IS NULL
RETURNING id, student_id, course_id, page_id, client_session_id, idempotency_key, entered_at, left_at
`

type LeavePageVisitIfOpenParams struct {
	LeftAt    pgtype.Timestamptz
	ID        uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) LeavePageVisitIfOpen(ctx context.Context, arg LeavePageVisitIfOpenParams) (PageVisit, error) {
	row := q.db.QueryRow(ctx, leavePageVisitIfOpen, arg.LeftAt, arg.ID, arg.StudentID)
	var i PageVisit
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.PageID,
		&i.ClientSessionID,
		&i.IdempotencyKey,
		&i.EnteredAt,
		&i.LeftAt,
	)
	return i, err
}

const listPageVisits = `-- name: ListPageVisits :many
SELECT id, student_id, course_id, page_id, client_session_id, idempotency_key, entered_at, left_at
FROM page_visits
WHERE ($1::uuid IS NULL OR student_id = $1::uuid)
  AND ($2::uuid IS NULL OR course_id = $2::uuid)
  AND ($3::uuid IS NULL OR page_id = $3::uuid)
  AND ($4::uuid IS NULL OR client_session_id = $4::uuid)
  AND (
      $5::text IS NULL
      OR ($5::text = 'OPEN' AND left_at IS NULL)
      OR ($5::text = 'CLOSED' AND left_at IS NOT NULL)
  )
  AND ($6::timestamptz IS NULL OR entered_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR entered_at < $7::timestamptz)
ORDER BY entered_at DESC, id
LIMIT $9::int OFFSET $8::bigint
`

type ListPageVisitsParams struct {
	StudentID       pgtype.UUID
	CourseID        pgtype.UUID
	PageID          pgtype.UUID
	ClientSessionID pgtype.UUID
	Status          pgtype.Text
	EnteredFrom     pgtype.Timestamptz
	EnteredBefore   pgtype.Timestamptz
	Offset          int64
	Limit           int32
}

func (q *Queries) ListPageVisits(ctx context.Context, arg ListPageVisitsParams) ([]PageVisit, error) {
	rows, err := q.db.Query(ctx, listPageVisits,
		arg.StudentID,
		arg.CourseID,
		arg.PageID,
		arg.ClientSessionID,
		arg.Status,
		arg.EnteredFrom,
		arg.EnteredBefore,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageVisit
	for rows.Next() {
		var i PageVisit
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CourseID,
			&i.PageID,
			&i.ClientSessionID,
			&i.IdempotencyKey,
			&i.EnteredAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPageVisitStudent = `-- name: LockPageVisitStudent :one
SELECT id
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPageVisitStudent(ctx context.Context, studentID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPageVisitStudent, studentID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockPageVisitTarget = `-- name: LockPageVisitTarget :one
SELECT pages.id
FROM pages
JOIN courses ON courses.id = pages.course_id
WHERE pages.id = $1
  AND courses.id = $2
FOR KEY SHARE OF pages, courses
`

type LockPageVisitTargetParams struct {
	PageID   uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) LockPageVisitTarget(ctx context.Context, arg LockPageVisitTargetParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPageVisitTarget, arg.PageID, arg.CourseID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const openPageVisitForStudentSession = `-- name: OpenPageVisitForStudentSession :one
SELECT id, student_id, course_id, page_id, client_session_id, idempotency_key, entered_at, left_at
FROM page_visits
WHERE student_id = $1
  AND client_session_id = $2
  AND left_at IS NULL
FOR UPDATE
`

type OpenPageVisitForStudentSessionParams struct {
	StudentID       uuid.UUID
	ClientSessionID uuid.UUID
}

func (q *Queries) OpenPageVisitForStudentSession(ctx context.Context, arg OpenPageVisitForStudentSessionParams) (PageVisit, error) {
	row := q.db.QueryRow(ctx, openPageVisitForStudentSession, arg.StudentID, arg.ClientSessionID)
	var i PageVisit
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.PageID,
		&i.ClientSessionID,
		&i.IdempotencyKey,
		&i.EnteredAt,
		&i.LeftAt,
	)
	return i, err
}

const pageVisitByIDForStudent = `-- name: PageVisitByIDForStudent :one
SELECT id, student_id, course_id, page_id, client_session_id, idempotency_key, entered_at, left_at
FROM page_visits
WHERE id = $1
  AND student_id = $2
`

type PageVisitByIDForStudentParams struct {
	ID        uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) PageVisitByIDForStudent(ctx context.Context, arg PageVisitByIDForStudentParams) (PageVisit, error) {
	row := q.db.QueryRow(ctx, pageVisitByIDForStudent, arg.ID, arg.StudentID)
	var i PageVisit
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.PageID,
		&i.ClientSessionID,
		&i.IdempotencyKey,
		&i.EnteredAt,
		&i.LeftAt,
	)
	return i, err
}

const pageVisitByIdempotencyKey = `-- name: PageVisitByIdempotencyKey :one
SELECT id, student_id, course_id, page_id, client_session_id, idempotency_key, entered_at, left_at
FROM page_visits
WHERE student_id = $1
  AND idempotency_key = $2
`

type PageVisitByIdempotencyKeyParams struct {
	StudentID      uuid.UUID
	IdempotencyKey uuid.UUID
}

func (q *Queries) PageVisitByIdempotencyKey(ctx context.Context, arg PageVisitByIdempotencyKeyParams) (PageVisit, error) {
	row := q.db.QueryRow(ctx, pageVisitByIdempotencyKey, arg.StudentID, arg.IdempotencyKey)
	var i PageVisit
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.PageID,
		&i.ClientSessionID,
		&i.IdempotencyKey,
		&i.EnteredAt,
		&i.LeftAt,
	)
	return i, err
}
