name: sciedu-stage

services:
  backend:
    image: "nycusdc/sciedu-backend:stage"
    networks:
      - internal
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENV=stage
      - ENVIRONMENT=stage
      - HOST=0.0.0.0
      - PORT=8080
      - BASE_URL=https://stage.sciedu.sdc.nycu.club
      - DATABASE_URL=postgres://postgres:password@postgres:5432/sciedu?sslmode=disable
      - LLM_URL=https://llm.stage.sciedu.sdc.nycu.club
      - MIGRATION_SOURCE=file:///app/migrations
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - GOOGLE_OAUTH_REDIRECT_URL=https://stage.sciedu.sdc.nycu.club/api/auth/callback
      - AUTH_REDIRECT_ALLOWLIST=https://stage.sciedu.sdc.nycu.club
      - ALLOW_ORIGINS=*.sciedu.sdc.nycu.club
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-backend-stage.rule=Host(`stage.sciedu.sdc.nycu.club`) && PathPrefix(`/api`)"
      - "traefik.http.routers.sciedu-backend-stage.entrypoints=websecure"
      - "traefik.http.routers.sciedu-backend-stage.tls=true"
      - "traefik.http.routers.sciedu-backend-stage.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-backend-stage.loadbalancer.server.port=8080"
      - "vector.enable=true"
  postgres:
    image: postgres:18.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sciedu
    networks:
      - internal

networks:
  internal:
  traefik:
    external: true
