// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chat

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID         uuid.UUID
	ChatID     uuid.UUID
	PreviousID pgtype.UUID
	Content    pgtype.Text
	Role       interface{}
	Status     string
	CreatedAt  pgtype.Timestamptz
}
